# Researcher Feedback

This page describes the meeting held on Friday, August 11, 2023 at Penn State that followed an [Open Science Bootcamp](https://penn-state-open-science/bootcamp-2023/).

The meeting sought feedback from the community on the topic:

"Making shared data about human participants maximally useful for secondary research"

## Participants

- Rick Gilmore, Penn State, Department of Psychology
- Briana Wham, Penn State, University Libraries
- Kevin Clair, Penn State, University Libraries
- Jeff Spies, Principal, 221b (via Zoom)
- Jenae Neiderhiser, Penn State, Department of Psychology
- Doug Teti, Penn State, Department of Human Development and Family Studies
- Nicole Lazar, Penn State, Department of Statistics
- C. Lee Giles, Penn State, Professor of Information Science and Technology
- Deborah Ehrenthal, Professor of Biobehavioral Health, Director, Socail Science Research Institute
- Alaina Pearce, Assistant Research Professor, Department of Nutritional Sciences

## Themes

Several invitees with specific data and metadata perspectives were unable to attend, the team shifted the focus to a discussion of what current Databrary offers researchers in terms of restricted access data storage and sharing and the systematic reporting of some core demographic data elements.

## Findings

